name: develop-body

on:
  push:
    tags:
      - 'v*.*.*_goji'
      - 'v*.*.*_all'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          logout: true
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./dockers/coctohug-goji/dockerfile
          context: ./dockers/coctohug-goji
          platforms: linux/amd64
          push: true
          build-args: |
            "CODE_BRANCH=3be896d4dcb48a734f8d2a901ab5648201fbd4d7"
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/coctohug-goji:develop
