name: develop-body

on:
  push:
    tags:
      - 'v*.*.*_nchain'
      - 'v*.*.*_all'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          logout: true
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./dockers/coctohug-nchain/dockerfile
          context: ./dockers/coctohug-nchain
          platforms: linux/amd64
          push: true
          build-args: |
            "CODE_BRANCH=0.1.4"
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/coctohug-nchain:develop
